import enum, uuid
from datetime import datetime
from sqlalchemy import String, DateTime, Integer, Float, Boolean, ForeignKey, Text, JSON, Enum
from sqlalchemy.orm import Mapped, mapped_column
from app.db.session import Base

def uid() -> str: return str(uuid.uuid4())
def now() -> datetime: return datetime.utcnow()
class RoleName(str, enum.Enum): admin="admin"; operator="operator"; technician="technician"; viewer="viewer"
class RobotStatus(str, enum.Enum): active="active"; idle="idle"; paused="paused"; charging="charging"; offline="offline"; error="error"; maintenance="maintenance"; emergency_stopped="emergency_stopped"
class TaskStatus(str, enum.Enum): pending="pending"; assigned="assigned"; queued="queued"; in_progress="in_progress"; paused="paused"; completed="completed"; failed="failed"; cancelled="cancelled"
class AlertSeverity(str, enum.Enum): info="info"; warning="warning"; critical="critical"
class AlertStatus(str, enum.Enum): open="open"; acknowledged="acknowledged"; resolved="resolved"; dismissed="dismissed"
class User(Base):
    __tablename__="users"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); email: Mapped[str]=mapped_column(String, unique=True, index=True); name: Mapped[str]=mapped_column(String); hashed_password: Mapped[str]=mapped_column(String); role: Mapped[RoleName]=mapped_column(Enum(RoleName), default=RoleName.viewer); is_active: Mapped[bool]=mapped_column(Boolean, default=True); last_login: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=now)
class Robot(Base):
    __tablename__="robots"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); code: Mapped[str]=mapped_column(String, unique=True, index=True); name: Mapped[str]=mapped_column(String); model: Mapped[str]=mapped_column(String, default="AMR-X"); serial_number: Mapped[str]=mapped_column(String, default=""); description: Mapped[str]=mapped_column(Text, default=""); status: Mapped[RobotStatus]=mapped_column(Enum(RobotStatus), default=RobotStatus.idle); operational_mode: Mapped[str]=mapped_column(String, default="autonomous"); battery_percentage: Mapped[float]=mapped_column(Float, default=80); battery_voltage: Mapped[float]=mapped_column(Float, default=24); current_speed: Mapped[float]=mapped_column(Float, default=0); maximum_speed: Mapped[float]=mapped_column(Float, default=1.5); temperature: Mapped[float]=mapped_column(Float, default=35); cpu_usage: Mapped[float]=mapped_column(Float, default=20); memory_usage: Mapped[float]=mapped_column(Float, default=30); x: Mapped[float]=mapped_column(Float, default=100); y: Mapped[float]=mapped_column(Float, default=100); heading: Mapped[float]=mapped_column(Float, default=0); floor: Mapped[str]=mapped_column(String, default="1"); zone: Mapped[str]=mapped_column(String, default="Storage Zone A"); current_task: Mapped[str|None]=mapped_column(String, nullable=True); connection_status: Mapped[str]=mapped_column(String, default="online"); ip_address: Mapped[str]=mapped_column(String, default=""); firmware_version: Mapped[str]=mapped_column(String, default="1.0.0"); last_seen: Mapped[datetime]=mapped_column(DateTime, default=now); created_at: Mapped[datetime]=mapped_column(DateTime, default=now); updated_at: Mapped[datetime]=mapped_column(DateTime, default=now, onupdate=now)
class RobotCommand(Base):
    __tablename__="robot_commands"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); robot_id: Mapped[str]=mapped_column(String, ForeignKey("robots.id"), index=True); command: Mapped[str]=mapped_column(String); parameters: Mapped[dict]=mapped_column(JSON, default=dict); status: Mapped[str]=mapped_column(String, default="queued"); requested_by: Mapped[str|None]=mapped_column(String, ForeignKey("users.id"), nullable=True); requested_at: Mapped[datetime]=mapped_column(DateTime, default=now); executed_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); response: Mapped[dict]=mapped_column(JSON, default=dict)
class Telemetry(Base):
    __tablename__="robot_telemetry"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); robot_id: Mapped[str]=mapped_column(String, ForeignKey("robots.id"), index=True); timestamp: Mapped[datetime]=mapped_column(DateTime, default=now, index=True); battery_percentage: Mapped[float]=mapped_column(Float); battery_voltage: Mapped[float]=mapped_column(Float); temperature: Mapped[float]=mapped_column(Float); speed: Mapped[float]=mapped_column(Float); x: Mapped[float]=mapped_column(Float); y: Mapped[float]=mapped_column(Float); heading: Mapped[float]=mapped_column(Float); cpu_usage: Mapped[float]=mapped_column(Float); memory_usage: Mapped[float]=mapped_column(Float); connection_quality: Mapped[float]=mapped_column(Float, default=100); current_draw: Mapped[float]=mapped_column(Float, default=0); distance_travelled: Mapped[float]=mapped_column(Float, default=0)
class FleetTask(Base):
    __tablename__="tasks"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); code: Mapped[str]=mapped_column(String, unique=True); title: Mapped[str]=mapped_column(String); description: Mapped[str]=mapped_column(Text, default=""); task_type: Mapped[str]=mapped_column(String, default="delivery"); priority: Mapped[str]=mapped_column(String, default="normal"); status: Mapped[TaskStatus]=mapped_column(Enum(TaskStatus), default=TaskStatus.pending); assigned_robot_id: Mapped[str|None]=mapped_column(String, ForeignKey("robots.id"), nullable=True); source_zone: Mapped[str]=mapped_column(String, default="Storage Zone A"); destination_zone: Mapped[str]=mapped_column(String, default="Packing Area"); source_x: Mapped[float]=mapped_column(Float, default=100); source_y: Mapped[float]=mapped_column(Float, default=100); destination_x: Mapped[float]=mapped_column(Float, default=700); destination_y: Mapped[float]=mapped_column(Float, default=300); progress_percentage: Mapped[int]=mapped_column(Integer, default=0); created_by: Mapped[str|None]=mapped_column(String, ForeignKey("users.id"), nullable=True); assigned_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); started_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); completed_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); failed_reason: Mapped[str|None]=mapped_column(Text, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=now); updated_at: Mapped[datetime]=mapped_column(DateTime, default=now, onupdate=now)
class Alert(Base):
    __tablename__="alerts"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); robot_id: Mapped[str|None]=mapped_column(String, ForeignKey("robots.id"), nullable=True); code: Mapped[str]=mapped_column(String); title: Mapped[str]=mapped_column(String); message: Mapped[str]=mapped_column(Text); category: Mapped[str]=mapped_column(String, default="system"); severity: Mapped[AlertSeverity]=mapped_column(Enum(AlertSeverity), default=AlertSeverity.info); status: Mapped[AlertStatus]=mapped_column(Enum(AlertStatus), default=AlertStatus.open); acknowledged_by: Mapped[str|None]=mapped_column(String, nullable=True); acknowledged_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); resolved_by: Mapped[str|None]=mapped_column(String, nullable=True); resolved_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); resolution_notes: Mapped[str|None]=mapped_column(Text, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=now); updated_at: Mapped[datetime]=mapped_column(DateTime, default=now, onupdate=now)
class MaintenanceRecord(Base):
    __tablename__="maintenance_records"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); robot_id: Mapped[str]=mapped_column(String, ForeignKey("robots.id")); type: Mapped[str]=mapped_column(String, default="inspection"); title: Mapped[str]=mapped_column(String); issue_description: Mapped[str]=mapped_column(Text, default=""); diagnosis: Mapped[str]=mapped_column(Text, default=""); repair_action: Mapped[str]=mapped_column(Text, default=""); technician: Mapped[str|None]=mapped_column(String, nullable=True); status: Mapped[str]=mapped_column(String, default="scheduled"); priority: Mapped[str]=mapped_column(String, default="normal"); parts_replaced: Mapped[str]=mapped_column(Text, default=""); cost: Mapped[float]=mapped_column(Float, default=0); downtime: Mapped[float]=mapped_column(Float, default=0); scheduled_date: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); started_date: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); completed_date: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); next_service_date: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); notes: Mapped[str]=mapped_column(Text, default=""); created_at: Mapped[datetime]=mapped_column(DateTime, default=now); updated_at: Mapped[datetime]=mapped_column(DateTime, default=now, onupdate=now)
class AuditLog(Base):
    __tablename__="audit_logs"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); user_id: Mapped[str|None]=mapped_column(String, nullable=True); action: Mapped[str]=mapped_column(String); entity_type: Mapped[str]=mapped_column(String); entity_id: Mapped[str|None]=mapped_column(String, nullable=True); description: Mapped[str]=mapped_column(Text); ip_address: Mapped[str|None]=mapped_column(String, nullable=True); meta: Mapped[dict]=mapped_column(JSON, default=dict); timestamp: Mapped[datetime]=mapped_column(DateTime, default=now)
class RefreshToken(Base):
    __tablename__="refresh_tokens"
    id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); user_id: Mapped[str]=mapped_column(String); token: Mapped[str]=mapped_column(String, unique=True); expires_at: Mapped[datetime]=mapped_column(DateTime); revoked: Mapped[bool]=mapped_column(Boolean, default=False)
