from abc import ABC, abstractmethod
class RobotAdapter(ABC):
    @abstractmethod
    async def connect(self): ...
    @abstractmethod
    async def disconnect(self): ...
    @abstractmethod
    async def get_status(self, robot_id: str): ...
    @abstractmethod
    async def get_telemetry(self, robot_id: str): ...
    @abstractmethod
    async def send_command(self, robot_id: str, command: str, parameters: dict): ...
    @abstractmethod
    async def assign_task(self, robot_id: str, task_id: str): ...
    @abstractmethod
    async def get_camera_source(self, robot_id: str): ...
    @abstractmethod
    async def health_check(self): ...
class MQTTRobotAdapter(RobotAdapter): pass
class RESTRobotAdapter(RobotAdapter): pass
class ROS2RobotAdapter(RobotAdapter): pass
